### ISSUE TITLE
真好！如果不依赖 Developer Express 就好了。。。

### ISSUE THREAD

**Issue by edwinyzh** [yanjiu-xyz/DevDataPager#1]
请问只用到 Developer Express 里面的绘图函数，还是用了里面的控件？有没有计划移除对 Developer Express 的依赖？毕竟那个不太普遍。谢谢。

**Comment by yanjiu-xyz** [comment]
用了dev绘图函数,还有一个皮肤控件支持,我在考虑加一个编译指令来开关dev的依赖

**Comment by yanjiu-xyz** [comment]
你好已改为默认不使用 Developer Express 的依赖,可在Defs.inc中开关

**Comment by edwinyzh** [comment]
哇！阁下好快！XE4下面编译安装通过，demo也编译运行通过！感谢！
